### PR TITLE
Use VMC standalone if found

### PR DESCRIPTION
**Pull request by benedikt-voelkel**
* account for VMC standalone

### CODE REVIEW

**Comment by benedikt-voelkel** [comment]
@ihrivnac @sawenzel @davidrohr

**Review by sawenzel — APPROVED** [review]

**Review by davidrohr — APPROVED** [review]

**Comment by davidrohr** [comment]
Who can merge this?
@ktf @pzhristov

**Comment by ktf** [comment]
in principle we  should do it on a branch called:

```
alice/<base-tag>
```

I can create it for you if  you tell me what `<base-tag>` we should use.

**Comment by benedikt-voelkel** [comment]
@pzhristov Is there any convention for the tagging?

I will change the recipe to that tag then as well in https://github.com/alisw/alidist/pull/3640

**Comment by ktf** [comment]
Conventions here:

https://github.com/alisw/alidist#guidelines-for-contributing-recipes

**Comment by benedikt-voelkel** [comment]
Thanks, I reckon in that case we should make `v1.4-alice1`?!

**Comment by ktf** [comment]
I created for you alice/v1.4 as a branch. Can you move this PR there? We  can then tag it with v1.4-alice1.

**Comment by ktf** [comment]
Ok, I can actually move the PR myself. Do you actually want  the two extra commits from master?

**Comment by benedikt-voelkel** [comment]
To me the additional commits don't seem to introduce significant changes or even breaking of interfaces. So I think we can include them, right @sawenzel ? Or whom should we contact in this case?

**Comment by ihrivnac** [comment]
I copy my comment from alidist PR here.
The dependence on VMV here is surprising; I looked in the code and the only usage of VMC is to access mag field in GeneratorCosmics:
 ```c++
 //
  auto fld = TGeoGlobalMagField::Instance()->GetField();
  if (TVirtualMC::GetMC() && TVirtualMC::GetMC()->GetMagField()) {
    fld = TVirtualMC::GetMC()->GetMagField();
  }
```
Does it make sense? I thought, that we always define field via TGeo and then set it to VMC.

**Comment by benedikt-voelkel** [comment]
@ktf let's merge this and come back to it if we want to remove the VMC dependency afterwards.

**Comment by ktf** [comment]
I created the new tag:

https://github.com/AliceO2Group/AEGIS/releases/tag/v1.4-alice1


Ciao,
Giulio


On Fri, Dec 10, 2021 at 09:10:16, benedikt-voelkel ***@***.***

**Comment by benedikt-voelkel** [comment]
Ok, I will update to that tag in https://github.com/alisw/alidist/pull/3640

**Pull request merged**
